name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos!
on: push
jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
      - run: echo "Se está ejecutando la rama: ${{ github.ref }}"
      - run: echo "El nombre del workflow es: ${{ github.workflow }}"
      - run: echo "El workflow fue activado por: ${{ github.actor }}"
      - run: echo "El resultado del paso anterior fue: ${{ steps.previous_step.outputs.resultado }}"
